import test from 'node:test';
import assert from 'node:assert/strict';
import {loadPreviewImage} from '../src/image-resource.mjs';
const blob=new Blob(['fixture'],{type:'image/png'});
function setup(decode=()=>Promise.resolve(),width=1){const revoked=[],image={src:'',naturalWidth:width,naturalHeight:1,decode};return {revoked,image,options:{width:1,height:1,createURL:()=> 'blob:owned',revokeURL:u=>revoked.push(u),createImage:()=>image}};}
test('decoded preview owns URL until idempotent disposal',async()=>{const s=setup(),result=await loadPreviewImage(blob,s.options);assert.equal(result.url,'blob:owned');assert.equal(s.revoked.length,0);result.dispose();result.dispose();assert.deepEqual(s.revoked,['blob:owned']);assert.equal(s.image.src,'');});
test('decode failure dimension mismatch and synchronous exceptions release URL',async()=>{for(const s of [setup(()=>Promise.reject(Error('decode'))),setup(undefined,2),setup(()=>{throw Error('sync');})]){await assert.rejects(loadPreviewImage(blob,s.options));assert.deepEqual(s.revoked,['blob:owned']);}});
test('abort and timeout release URL and ignore late decode',async()=>{let done;const s=setup(()=>new Promise(resolve=>done=resolve)),c=new AbortController();const pending=loadPreviewImage(blob,{...s.options,signal:c.signal});c.abort();await assert.rejects(pending,{name:'AbortError'});done();await Promise.resolve();assert.deepEqual(s.revoked,['blob:owned']);const slow=setup(()=>new Promise(()=>{}));await assert.rejects(loadPreviewImage(blob,{...slow.options,timeoutMs:5}),/timed out/);assert.equal(slow.revoked.length,1);});
test('invalid inputs and pre-cancelled requests allocate no URL',async()=>{const s=setup(),c=new AbortController();c.abort();await assert.rejects(loadPreviewImage(blob,{...s.options,signal:c.signal}));await assert.rejects(loadPreviewImage(new Blob(['<svg/>'],{type:'image/svg+xml'}),s.options));await assert.rejects(loadPreviewImage(blob,{...s.options,width:9000}));assert.equal(s.revoked.length,0);assert.equal(s.image.src,'');});
