import {createHandler} from '../index.mjs';import * as adapter from '../vcs.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import * as fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';import {detectRepository,listReferences,listHistory} from '../vcs.mjs';
test('local remote tracking refs pin commits without contacting remote or modifying repository',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'vcs-remote-refs-'));const git=(...args)=>execFileSync('git',['-C',root,...args],{encoding:'utf8',windowsHide:true});
 try{git('init','-q');git('config','user.name','Test');git('config','user.email','t@example.test');await fs.writeFile(path.join(root,'file'),'one');git('add','.');git('commit','-qm','one');const first=git('rev-parse','HEAD').trim();git('update-ref','refs/remotes/origin/main',first);git('symbolic-ref','refs/remotes/origin/HEAD','refs/remotes/origin/main');git('remote','add','origin','invalid-transport://never-contact');git('tag','origin/main');await fs.writeFile(path.join(root,'file'),'two');git('commit','-qam','two');const second=git('rev-parse','HEAD').trim();const repo=await detectRepository(root),status=git('status','--porcelain'),index=git('ls-files','--stage'),refs=git('show-ref');
 const call=createHandler({sessions:{get:()=>({header:{cwd:root}})}},adapter),discovery=await call('vcs/repositories',{sessionId:'s'});assert.equal(discovery.ok,true);const payload={sessionId:'s',repositoryId:discovery.value.repositories[0].id};assert.equal((await call('vcs/references',{...payload,sessionId:'foreign'})).error.code,'vcs/rediscover-required');assert.equal((await call('vcs/references',{...payload,url:'https://example.test'})).error.code,'vcs/invalid-request');
 const response=await call('vcs/references',payload);assert.equal(response.ok,true);const result=response.value;const remote=result.references.find(r=>r.name==='refs/remotes/origin/main');assert.equal(remote.kind,'remote');assert.equal(remote.commit,first);assert.equal(result.references.find(r=>r.name==='refs/remotes/origin/HEAD').commit,first);assert.equal(result.references.find(r=>r.name==='refs/tags/origin/main').kind,'tag');assert.equal(git('show-ref'),refs);assert.equal(git('status','--porcelain'),status);assert.equal(git('ls-files','--stage'),index);
 git('update-ref','refs/remotes/origin/main',second);assert.equal((await listReferences(repo)).references.find(r=>r.name===remote.name).commit,second);assert.equal((await listHistory(repo,{snapshot:remote.commit})).commits[0].id,first);
 }finally{await fs.rm(root,{recursive:true,force:true});}
});
