import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';
import {XMLParser} from 'fast-xml-parser';
import {parseSvnLogPage} from '../src/svn-log.mjs';
import {relativeSvnPath} from '../src/svn-path.mjs';
import {parseSvnDetail} from '../src/svn-detail.mjs';
import {parseSvnPropertyNames} from '../src/svn-property-names.mjs';
import {planSvnComparison} from '../src/svn-comparison-plan.mjs';
import {planSvnLog,planSvnDetail} from '../src/svn-log-plan.mjs';
test('local SVN path history skips unrelated revisions and pins numeric snapshot',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'dsh-svn-history-'));t.after(()=>fs.rm(root,{recursive:true,force:true,maxRetries:5}));
 const run=(name,args,cwd=root)=>{const r=spawnSync(name,args,{cwd,encoding:'utf8',windowsHide:true,timeout:20000,env:{...process.env,LC_ALL:process.platform==='linux'?'C.UTF-8':'en_US.UTF-8'}});assert.equal(r.status,0,r.stderr);return r.stdout;};
 const repository=path.join(root,'repo'),wc=path.join(root,'wc');run('svnadmin',['create',repository]);run('svn',['checkout','--non-interactive',pathToFileURL(repository).href,wc]);
 const emptyXml=run('svn',['log','--non-interactive','--no-auth-cache','--xml','-r','0:0','--',pathToFileURL(repository).href+'@0']);
 const emptyPage=parseSvnLogPage(emptyXml,{snapshot:'0'});assert.equal(emptyPage.nextRevision,null);assert.ok(emptyPage.entries.every(e=>e.revision==='0'));
 const name='中文 @ percent%.txt',file=path.join(wc,name);
 const svn=args=>run('svn',['--non-interactive','--no-auth-cache',...args],wc);
 await fs.writeFile(file,'r1');await fs.writeFile(path.join(wc,'other'),'r1');svn(['add','--',name+'@','other']);svn(['commit','-m','r1']);
 await fs.writeFile(path.join(wc,'other'),'r2');svn(['commit','-m','r2']);
 await fs.writeFile(file,'r3');svn(['commit','-m','r3']);
 await fs.writeFile(file,'r4');svn(['commit','-m','r4']);
 const parser=new XMLParser({ignoreAttributes:false,parseAttributeValue:false,isArray:name=>name==='logentry'});
 // Test-only transport substitution: production planner still rejects file:// roots.
 const planningRoot='https://example.test/fixture';
 const executePlan=plan=>{const args=[...plan.args];assert.ok(args.at(-1).startsWith(planningRoot+'/'));args[args.length-1]=pathToFileURL(repository).href+args.at(-1).slice(planningRoot.length);return run('svn',args,wc);};
 const planOptions={root:planningRoot,scope:'/',path:'/'+name,snapshot:'3'};
 const pageAt=cursor=>{const plan=planSvnLog({...planOptions,cursor,limit:1});return parseSvnLogPage(executePlan(plan),plan);};
 const status=svn(['status','--xml']),info=svn(['info','--xml','--',name+'@']);
 const detailPlan=planSvnDetail({...planOptions,revision:'3'});
 const plannedDetail=parseSvnDetail(executePlan(detailPlan),detailPlan);assert.equal(plannedDetail.message,'r3');assert.equal(plannedDetail.changes[0].path,'/'+name);
 const page=pageAt('3');assert.equal(page.snapshot,'3');assert.equal(page.nextRevision,'2');assert.deepEqual(page.entries.map(e=>[e.revision,e.message]),[['3','r3']]);
 const next=pageAt(page.nextRevision);assert.equal(next.snapshot,'3');assert.equal(next.nextRevision,null);assert.deepEqual(next.entries.map(e=>[e.revision,e.message]),[['1','r1']]);
 assert.equal(svn(['cat','-r','3','--',name+'@3']),'r3');assert.equal(await fs.readFile(file,'utf8'),'r4');
 assert.deepEqual(parser.parse(svn(['status','--xml'])),parser.parse(status));assert.deepEqual(parser.parse(svn(['info','--xml','--',name+'@'])),parser.parse(info));
 // Fixture writes create a copy at r5; subsequent review commands remain read-only.
 svn(['copy','--',name+'@','copy.txt']);svn(['commit','-m','r5 copy']);
 await fs.writeFile(path.join(wc,'copy.txt'),'r6');svn(['commit','-m','r6 edit']);
 const copyStatus=svn(['status','--xml']),copyInfo=svn(['info','--xml','--','copy.txt@']);
 const copyLog=stop=>parser.parse(svn(['log','--xml','--verbose',...(stop?['--stop-on-copy']:[]),'-r','6:0','--','copy.txt@6'])).log.logentry;
 const copyOptions={root:planningRoot,scope:'/',path:'/copy.txt',snapshot:'6',limit:1};
 const copyFirstPlan=planSvnLog(copyOptions);const copyFirst=parseSvnLogPage(executePlan(copyFirstPlan),copyFirstPlan);
 assert.deepEqual(copyFirst.entries.map(e=>e.revision),['6']);assert.equal(copyFirst.nextRevision,'5');
 const copyNextPlan=planSvnLog({...copyOptions,cursor:copyFirst.nextRevision});const copyNext=parseSvnLogPage(executePlan(copyNextPlan),copyNextPlan);
 assert.deepEqual(copyNext.entries.map(e=>e.revision),['5']);assert.equal(copyNext.nextRevision,null);
 const creationPlan=planSvnDetail({...copyOptions,revision:'5'});const creationDetail=parseSvnDetail(executePlan(creationPlan),creationPlan);
 assert.equal(creationDetail.changes[0].copyFromPath,'/'+name);assert.equal(creationDetail.changes[0].copyFromRevision,'4');
 const stopped=copyLog(true);assert.deepEqual(stopped.map(e=>e['@_revision']),['6','5']);
 const copy=stopped[1].paths.path;assert.equal(copy['@_action'],'A');assert.equal(copy['@_copyfrom-path'],'/'+name);assert.equal(copy['@_copyfrom-rev'],'4');
 // Positive control proves the default command would cross the copy boundary.
 assert.deepEqual(copyLog(false).map(e=>e['@_revision']),['6','5','4','3','1']);
 assert.equal(svn(['cat','-r','5','--','copy.txt@6']),'r4');
 assert.deepEqual(parser.parse(svn(['status','--xml'])),parser.parse(copyStatus));assert.deepEqual(parser.parse(svn(['info','--xml','--','copy.txt@'])),parser.parse(copyInfo));assert.equal(await fs.readFile(path.join(wc,'copy.txt'),'utf8'),'r6');
 // Delete only in the temporary fixture; use the repository URL for the old identity.
 svn(['delete','--','copy.txt']);svn(['commit','-m','r7 deletion']);
 const deletedStatus=parser.parse(svn(['status','--xml']));
 // SVN renders the unreserved tilde literally (Windows runner uses RUNNER~1).
 const rootUrl=pathToFileURL(repository).href.replace(/%7E/gi,'~'),copyUrl=rootUrl+'/copy.txt';
 const deletion=parser.parse(svn(['log','--xml','--verbose','-r','7:7','--',rootUrl+'@7'])).log.logentry[0];
 assert.equal(deletion.paths.path['@_action'],'D');assert.equal(deletion.paths.path['#text'],'/copy.txt');
 assert.equal(svn(['cat','-r','6','--',copyUrl+'@6']),'r6');
 await assert.rejects(fs.stat(path.join(wc,'copy.txt')),{code:'ENOENT'});
 assert.deepEqual(parser.parse(svn(['status','--xml'])),deletedStatus);
 await fs.writeFile(path.join(wc,'copy.txt'),'new identity r8');svn(['add','--','copy.txt']);svn(['commit','-m','r8 recreate']);
 const recreatedStatus=parser.parse(svn(['status','--xml']));
 const newHistory=parser.parse(svn(['log','--xml','--verbose','--stop-on-copy','-r','8:0','--',copyUrl+'@8'])).log.logentry;
 assert.deepEqual(newHistory.map(e=>e['@_revision']),['8']);assert.equal(newHistory[0].paths.path['@_action'],'A');assert.equal(newHistory[0].paths.path['@_copyfrom-rev'],undefined);
 const oldHistory=parser.parse(svn(['log','--xml','--stop-on-copy','-r','6:0','--',copyUrl+'@6'])).log.logentry;assert.deepEqual(oldHistory.map(e=>e['@_revision']),['6','5']);
 assert.equal(svn(['cat','-r','6','--',copyUrl+'@6']),'r6');assert.equal(svn(['cat','-r','8','--',copyUrl+'@8']),'new identity r8');
 assert.deepEqual(parser.parse(svn(['status','--xml'])),recreatedStatus);assert.equal(await fs.readFile(path.join(wc,'copy.txt'),'utf8'),'new identity r8');
 // A path-scoped verbose log still describes the entire shared revision.
 for(const directory of ['scope','scope-other']){await fs.mkdir(path.join(wc,directory));await fs.writeFile(path.join(wc,directory,'file'),'r9');}
 svn(['add','--','scope','scope-other']);svn(['commit','-m','r9 shared scope']);
 const scopedStatus=parser.parse(svn(['status','--xml']));
 const scopedXml=svn(['log','--xml','--verbose','-r','9:9','--',rootUrl+'/scope@9']);
 const scoped=parser.parse(scopedXml).log.logentry[0];
 const paths=scoped.paths.path.map(p=>p['#text']);
 assert.ok(paths.includes('/scope-other/file'),'Positive control: verbose log exposes paths outside query scope');
 const detail=parseSvnDetail(scopedXml,{scope:'/scope',revision:'9'});assert.equal(detail.message,'r9 shared scope');
 const allowed=detail.changes.map(p=>p.path);assert.deepEqual(allowed.sort(),['/scope','/scope/file']);
 assert.deepEqual(allowed.map(p=>relativeSvnPath(p,'/scope')),['','file']);
 assert.deepEqual(parser.parse(svn(['status','--xml'])),scopedStatus);
 svn(['copy','--','scope-other/file','scope/imported']);svn(['commit','-m','r10 cross-scope copy']);
 const copyScopeStatus=parser.parse(svn(['status','--xml']));
 const crossXml=svn(['log','--xml','--verbose','-r','10:10','--',rootUrl+'/scope@10']);
 const cross=parser.parse(crossXml).log.logentry[0];
 assert.equal(cross.paths.path['@_copyfrom-path'],'/scope-other/file');
 assert.deepEqual(parseSvnDetail(crossXml,{scope:'/scope',revision:'10'}).changes,[{path:'/scope/imported',action:'A',kind:'file',copySourceOutsideScope:true,textModified:cross.paths.path['@_text-mods'],propertiesModified:cross.paths.path['@_prop-mods']}]);
 assert.deepEqual(parser.parse(svn(['status','--xml'])),copyScopeStatus);
 svn(['delete','--','scope/imported']);await fs.writeFile(path.join(wc,'scope','imported'),'replacement r11');svn(['add','--','scope/imported']);svn(['commit','-m','r11 replacement']);
 const replacementStatus=parser.parse(svn(['status','--xml']));
 const replacement=parseSvnDetail(svn(['log','--xml','--verbose','-r','11:11','--',rootUrl+'/scope@11']),{scope:'/scope',revision:'11'});
 assert.equal(replacement.pathsAvailable,true);assert.deepEqual(replacement.changes,[{path:'/scope/imported',action:'R',kind:'file',textModified:'true',propertiesModified:'false'}]);
 assert.equal(svn(['cat','-r','10','--',rootUrl+'/scope/imported@10']),'r9');
 assert.equal(svn(['cat','-r','11','--',rootUrl+'/scope/imported@11']),'replacement r11');
 assert.deepEqual(parser.parse(svn(['status','--xml'])),replacementStatus);assert.equal(await fs.readFile(path.join(wc,'scope','imported'),'utf8'),'replacement r11');
 const crossPlan=planSvnComparison(parseSvnDetail(crossXml,{scope:'/scope',revision:'10'}).changes,{scope:'/scope',revision:'10',path:'/scope/imported'});
 assert.deepEqual(crossPlan.left,{empty:true});assert.equal(crossPlan.right.path,'/scope/imported');
 const readSide=side=>side.empty?'':svn(['cat','-r',side.revision,'--',rootUrl+side.path.split('/').map(encodeURIComponent).join('/')+'@'+side.pegRevision]);
 assert.equal(readSide(crossPlan.right),'r9');
 for(const [revision,target,action,left,right] of [['1','/'+name,'A','','r1'],['3','/'+name,'M','r1','r3'],['7','/copy.txt','D','r6',''],['11','/scope/imported','R','r9','replacement r11']]){
  const detail=parseSvnDetail(svn(['log','--xml','--verbose','-r',revision+':'+revision,'--',rootUrl+'@11']),{scope:'/',revision});
  const plan=planSvnComparison(detail.changes,{scope:'/',revision,path:target});
  assert.equal(plan.action,action);assert.equal(readSide(plan.left),left);assert.equal(readSide(plan.right),right);
 }
 assert.deepEqual(parser.parse(svn(['status','--xml'])),replacementStatus);
 svn(['propset','review:test','property r12','--','scope/imported']);svn(['commit','-m','r12 property only']);
 const propertyStatus=parser.parse(svn(['status','--xml']));
 const propertyXml=svn(['log','--xml','--verbose','-r','12:12','--',rootUrl+'/scope@12']);
 const rawProperty=parser.parse(propertyXml).log.logentry[0].paths.path;
 assert.equal(rawProperty['@_text-mods'],'false');assert.equal(rawProperty['@_prop-mods'],'true');
 const propertyDetail=parseSvnDetail(propertyXml,{scope:'/scope',revision:'12'});
 assert.deepEqual(propertyDetail.changes,[{path:'/scope/imported',action:'M',kind:'file',textModified:'false',propertiesModified:'true'}]);
 const propertyPlan=planSvnComparison(propertyDetail.changes,{scope:'/scope',revision:'12',path:'/scope/imported'});
 assert.equal(readSide(propertyPlan.left),'replacement r11');assert.equal(readSide(propertyPlan.right),'replacement r11');
 const props=revision=>parser.parse(svn(['proplist','--xml','--verbose','-r',revision,'--',rootUrl+'/scope/imported@'+revision]));
 assert.notDeepEqual(props('11'),props('12'));assert.equal(props('12').properties.target.property['#text'],'property r12');
 assert.deepEqual(parser.parse(svn(['status','--xml'])),propertyStatus);
 const specialPath=path.join(wc,'scope','special');
 if(process.platform==='win32'){await fs.writeFile(specialPath,'link ../outside-target');svn(['add','--','scope/special']);await fs.writeFile(path.join(root,'special-value'),'*');svn(['propset','svn:special','--file',path.join(root,'special-value'),'--','scope/special']);}
 else{await fs.symlink('../outside-target',specialPath);svn(['add','--','scope/special']);}
 svn(['commit','-m','r13 special file']);
 const specialStatus=parser.parse(svn(['status','--xml']));
 const specialDetail=parseSvnDetail(svn(['log','--xml','--verbose','-r','13:13','--',rootUrl+'/scope@13']),{scope:'/scope',revision:'13'});
 assert.equal(specialDetail.changes[0].kind,'file');
 const specialProperties=parser.parse(svn(['proplist','--xml','--verbose','-r','13','--',rootUrl+'/scope/special@13']));
 assert.equal(specialProperties.properties.target.property['@_name'],'svn:special');
 assert.equal(svn(['cat','-r','13','--',rootUrl+'/scope/special@13']),'link ../outside-target');
 const namesXml=(suffix,revision)=>svn(['proplist','--xml','-r',revision,'--',rootUrl+suffix+'@'+revision]);
 const specialNamesXml=namesXml('/scope/special','13');
 assert.equal(parser.parse(specialNamesXml).properties.target['@_path'],rootUrl+'/scope/special','Names-only SVN target must match requested fixture URL');
 assert.deepEqual(parseSvnPropertyNames(specialNamesXml,{target:rootUrl+'/scope/special'}),{target:rootUrl+'/scope/special',names:['svn:special'],special:true});
 assert.deepEqual(parseSvnPropertyNames(namesXml('/scope/imported','12'),{target:rootUrl+'/scope/imported'}),{target:rootUrl+'/scope/imported',names:['review:test'],special:false});
 const emptyNames=namesXml('/scope/imported','11');
 assert.equal(parser.parse(emptyNames).properties.target,undefined);
 assert.throws(()=>parseSvnPropertyNames(emptyNames,{target:rootUrl+'/scope/imported'}));
 assert.deepEqual(parser.parse(svn(['status','--xml'])),specialStatus);
});
