import {runBoundedProcess} from '../src/bounded-process.mjs';import {createSvnRpc} from '../src/svn-rpc.mjs';import {XMLParser} from 'fast-xml-parser';import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {pathToFileURL} from 'node:url';import {spawnSync} from 'node:child_process';import {createSvnRuntime} from '../src/svn-runtime.mjs';
test('real offline SVN coordinator consent log detail comparison keep working copy unchanged',async()=>{
 const root=await mkdtemp(path.join(tmpdir(),'svn-runtime-'));try{const repository=path.join(root,'repo'),wc=path.join(root,'wc'),url=pathToFileURL(repository).href,planning='https://example.test/repo';
 const run=(cmd,args,cwd=root)=>{const r=spawnSync(cmd,args,{cwd,encoding:'utf8',windowsHide:true,timeout:15000,maxBuffer:2097152,env:{...process.env,LC_ALL:process.platform==='linux'?'C.UTF-8':'en_US.UTF-8'}});assert.equal(r.status,0,r.stderr);return r.stdout;};run('svnadmin',['create',repository]);run('svn',['checkout','--non-interactive',url,wc]);const svn=args=>run('svn',['--non-interactive','--no-auth-cache',...args],wc);await writeFile(path.join(wc,'file.txt'),'first');svn(['add','file.txt']);svn(['commit','-m','first']);await writeFile(path.join(wc,'file.txt'),'second');svn(['commit','-m','second']);await writeFile(path.join(wc,'file.txt'),'WORKING');const status=svn(['status','--xml']);let calls=0;
 // Test-only local substitution. No production file:// allowance or external requests.
 const identity={cwd:wc,root:planning,uuid:'12345678-1234-1234-1234-123456789abc',scope:'/'},runtime=createSvnRuntime({resolveIdentity:async()=>identity,transport:async(plan,{signal,maxBytes,timeoutMs})=>{signal?.throwIfAborted();assert.equal(maxBytes,2097152);assert.equal(timeoutMs,15000);const args=[...plan.args],target=args.at(-1);assert.ok(target.startsWith(planning));args[args.length-1]=url+target.slice(planning.length);calls++;let output=await runBoundedProcess('svn',['--non-interactive','--no-auth-cache',...args],{cwd:wc,signal,maxBytes,timeoutMs,env:{...process.env,LC_ALL:process.platform==='linux'?'C.UTF-8':'en_US.UTF-8'}});if(args[0]==='proplist'){const xml=output.toString('utf8');const returned=new XMLParser({ignoreAttributes:false}).parse(xml).properties?.target?.['@_path'];if(returned!==undefined){assert.equal(new URL(returned).protocol,'file:');assert.equal(decodeURIComponent(new URL(returned).pathname),decodeURIComponent(new URL(args.at(-1).slice(0,args.at(-1).lastIndexOf('@'))).pathname),'Offline SVN target differs: '+returned+' vs '+args.at(-1));}const variants=process.platform==='win32'?[url,url.slice(0,8)+url[8].toLowerCase()+url.slice(9),url.slice(0,8)+url[8].toUpperCase()+url.slice(9)]:[url];output=Buffer.from(returned===undefined?variants.reduce((text,localUrl)=>text.replaceAll(localUrl,planning),xml):xml.replaceAll(returned,target.slice(0,target.lastIndexOf('@'))));}return output;}}),address={sessionId:'s',repositoryId:'r'};
 const rpc=createSvnRpc(runtime),invoke=async(method,options={})=>{const result=await rpc('vcs/svn-'+method,{...address,...options});assert.equal(result.ok,true,JSON.stringify(result));return result.value;};assert.equal((await rpc('vcs/svn-log',{...address,snapshot:'2'})).ok,false);await assert.rejects(runtime.log(address,{snapshot:'2'}));assert.equal(calls,0);const offer=await invoke('describe'),grant=await invoke('approve',{offer:offer.offer,explicit:true}),options={token:grant.token,snapshot:'2'};const page=await invoke('log',{...options,limit:1});assert.equal(page.entries[0].message,'second');assert.equal(page.nextRevision,'1');const detail=await invoke('detail',{...options,revision:'2'}),comparison=await invoke('compare',{...options,revision:'2',id:detail.changes[0].id});assert.equal(comparison.left.text,'first');assert.equal(comparison.right.text,'second');assert.equal(await readFile(path.join(wc,'file.txt'),'utf8'),'WORKING');assert.deepEqual(new XMLParser({ignoreAttributes:false}).parse(svn(['status','--xml'])),new XMLParser({ignoreAttributes:false}).parse(status));
 await writeFile(path.join(wc,'file.txt'),'second');svn(['copy','file.txt','copy.txt']);svn(['commit','-m','copy']);await writeFile(path.join(wc,'copy.txt'),'copy edit');svn(['commit','-m','copy edit']);const copyOptions={token:grant.token,snapshot:'4',revision:'4'},copyDetail=await runtime.detail(address,copyOptions),trace=await runtime.trace(address,{...copyOptions,id:copyDetail.changes[0].id});assert.deepEqual(trace.entries.map(e=>e.revision),['4','3']);assert.equal(trace.stopOnCopy,true);svn(['delete','copy.txt']);svn(['commit','-m','deleted']);const deletionOptions={token:grant.token,snapshot:'5',revision:'5'},deletion=await runtime.detail(address,deletionOptions),deletedTrace=await runtime.trace(address,{...deletionOptions,id:deletion.changes[0].id});assert.equal(deletedTrace.pegRevision,'4');assert.deepEqual(deletedTrace.entries.map(e=>e.revision),['4','3']);
 await writeFile(path.join(wc,'binary.dat'),Buffer.from([0,255,1]));svn(['add','binary.dat']);svn(['commit','-m','binary']);const binaryOptions={token:grant.token,snapshot:'6',revision:'6'},binaryDetail=await invoke('detail',binaryOptions),binary=await invoke('compare',{...binaryOptions,id:binaryDetail.changes[0].id});assert.equal(binary.binary,true);assert.equal(binary.left.absent,true);assert.equal(binary.right.binary,true);const removed=await invoke('compare',{...deletionOptions,id:deletion.changes[0].id});assert.equal(removed.left.text,'copy edit');assert.equal(removed.right.absent,true);
 }finally{await rm(root,{recursive:true,force:true,maxRetries:5});}
});
