import React from 'react';
import {createRoot} from 'react-dom/client';
import HistoryPanel from '../src/HistoryPanel.jsx';
const calls=[],a='a'.repeat(40),b='b'.repeat(40),id='c'.repeat(64);
const row=(id,subject)=>({id,subject,author:'Tester',date:'2026-09-29T00:00:00+00:00',parents:[]});
let delayedResolve,delayedSignal,delayNext=false;
const rpc=async(endpoint,payload,signal)=>{
 calls.push({endpoint,payload});
 if(delayNext){delayNext=false;delayedSignal=signal;return new Promise(resolve=>{delayedResolve=resolve;});}
 if(endpoint==='vcs/history')return {snapshot:a,commits:payload.offset?[row(b,'Second commit')]:[row(a,'First commit')],nextOffset:payload.offset?null:1};
 if(endpoint==='vcs/commit')return {...row(payload.commit,'Details'),parents:[a,b],parent:payload.parentIndex?b:a,parentIndex:payload.parentIndex,changes:[{id,path:payload.parentIndex?'parent-two.txt':'example.txt',status:'added'}]};
 if(endpoint==='vcs/commit-compare')return {path:'example.txt',left:{label:'Empty',text:''},right:{label:a,text:'historical content'},binary:false};
 throw Error('Unexpected RPC');
};
const root=createRoot(document.querySelector('#root'));
root.render(<HistoryPanel sessionId="fixture" repositoryId="repo" rpc={rpc} t={key=>key} onRediscover={()=>{throw Error('Unexpected rediscovery');}}/>);
const wait=async fn=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,20));}throw Error('Timed out waiting for UI');};
const button=text=>[...document.querySelectorAll('button')].find(el=>el.textContent===text);
(async()=>{try{
 await wait(()=>button('First commit'));
 button('historyMore').click();await wait(()=>button('Second commit'));
 if(calls[1].payload.snapshot!==a||calls[1].payload.offset!==1)throw Error('Snapshot pagination mismatch');
 button('First commit').click();await wait(()=>button('added · example.txt'));
 button('added · example.txt').click();await wait(()=>document.querySelector('.vcs-text-comparison'));
 if(!document.querySelector('.vcs-text-comparison').textContent.includes('historical content'))throw Error('Missing historical content');
 const countBeforeFilter=calls.length;
 const input=document.querySelector('input[aria-label="commitFileSearch"]');
 const enter=value=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));};
 enter('no-matching-file');await wait(()=>!button('added · example.txt'));
 if(document.querySelector('.vcs-text-comparison'))throw Error('Filtered file retained old diff');
 enter('');await wait(()=>button('added · example.txt'));
 if(calls.length!==countBeforeFilter)throw Error('Filtering unexpectedly called RPC');
 const select=document.querySelector('select');select.value='1';select.dispatchEvent(new Event('change',{bubbles:true}));
 await wait(()=>button('added · parent-two.txt'));
 if(document.querySelector('.vcs-text-comparison'))throw Error('Old parent diff retained');
 if(calls.at(-1).payload.parentIndex!==1)throw Error('Parent selection not forwarded');
 delayNext=true;button('added · parent-two.txt').click();await wait(()=>delayedResolve);
 const staleResolve=delayedResolve,staleSignal=delayedSignal;delayedResolve=null;
 button('Second commit').click();await wait(()=>button('added · example.txt'));
 if(!staleSignal.aborted)throw Error('Switch failed to abort old diff');
 staleResolve({path:'STALE',left:{text:''},right:{text:'STALE'},binary:false});
 await new Promise(r=>setTimeout(r,40));if(document.querySelector('#root').textContent.includes('STALE'))throw Error('Stale response displayed');
 delayNext=true;button('added · example.txt').click();await wait(()=>delayedResolve);
 root.unmount();if(!delayedSignal.aborted)throw Error('Unmount failed to cancel');
 delayedResolve({path:'STALE',left:{text:''},right:{text:'STALE'}});
 document.querySelector('#report').textContent=JSON.stringify({pass:true,browser:navigator.userAgent,steps:['pagination','commit','file','diff','filter','parent','stale','unmount'],calls:calls.length});
 }catch(e){document.querySelector('#report').textContent=JSON.stringify({pass:false,error:String(e)});}})();
