import React from 'react';
import {createRoot} from 'react-dom/client';
import HistoryPanel from '../src/HistoryPanel.jsx';
const calls=[],a='a'.repeat(40),b='b'.repeat(40),id='c'.repeat(64);
const row=(id,subject)=>({id,subject,author:'Tester',date:'2026-09-29T00:00:00+00:00',parents:[]});
let delayedResolve,delayedSignal,delayNext=false;
const rpc=async(endpoint,payload,signal)=>{
 calls.push({endpoint,payload});
 if(delayNext){delayNext=false;delayedSignal=signal;return new Promise(resolve=>{delayedResolve=resolve;});}
 if(endpoint==='vcs/history')return {snapshot:a,commits:payload.offset?[row(b,'Second commit')]:[row(a,'First commit')],nextOffset:payload.offset?null:1};
 if(endpoint==='vcs/commit')return {...row(payload.commit,'Details'),parents:[a,b],parent:payload.parentIndex?b:a,parentIndex:payload.parentIndex,changes:[{id,path:payload.parentIndex?'parent-two.txt':'example.txt',status:'added'}]};
 if(endpoint==='vcs/commit-compare')return {path:'example.txt',left:{label:'Empty',text:''},right:{label:a,text:'historical content'},binary:false};
 throw Error('Unexpected RPC');
};
const root=createRoot(document.querySelector('#root'));
root.render(<HistoryPanel sessionId="fixture" repositoryId="repo" rpc={rpc} t={key=>key} onRediscover={()=>{throw Error('Unexpected rediscovery');}}/>);
const wait=async fn=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,20));}throw Error('Timed out waiting for UI');};
const button=text=>[...document.querySelectorAll('button')].find(el=>el.textContent===text);
(async()=>{try{
 await wait(()=>button('First commit'));
 const search=document.querySelector('input[aria-label="historySearch"]');
 const searchFor=value=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(search,value);search.dispatchEvent(new Event('input',{bubbles:true}));};
 searchFor('Second');await wait(()=>!button('First commit'));
 if(!button('historyMore')||calls.length!==1)throw Error('Search changed pagination or issued RPC');
 button('historyMore').click();await wait(()=>button('Second commit'));
 if(button('First commit'))throw Error('Pagination lost search condition');
 searchFor('missing');await wait(()=>!button('Second commit'));
 if(!document.querySelector('#root').textContent.includes('historyNoMatch'))throw Error('Missing scoped empty state');
 searchFor('');await wait(()=>button('First commit')&&button('Second commit'));
 if(calls.length!==2)throw Error('Search issued extra RPC');
 if(calls[1].payload.snapshot!==a||calls[1].payload.offset!==1)throw Error('Snapshot pagination mismatch');
 button('historyGraph').click();await wait(()=>document.querySelector('section[aria-label=historyGraph] ol button'));
 const graphButtons=[...document.querySelectorAll('section[aria-label=historyGraph] ol button')];
 graphButtons[1].click();await wait(()=>button('Second commit').getAttribute('aria-pressed')==='true'&&graphButtons[1].getAttribute('aria-current')==='true'&&button('added · example.txt'));
 if(calls.at(-1).endpoint!=='vcs/commit'||calls.at(-1).payload.commit!==b)throw Error('Graph selection did not load matching detail');
 const beforeFocus=calls.length;graphButtons[1].focus();graphButtons[1].dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true,cancelable:true}));
 if(document.activeElement!==graphButtons[0]||graphButtons[1].getAttribute('aria-current')!=='true'||calls.length!==beforeFocus)throw Error('Graph focus changed selected context');
 searchFor('First');await wait(()=>!button('added · example.txt')&&!document.querySelector('section[aria-label=historyGraph] [aria-current=true]'));
 if(calls.length!==beforeFocus)throw Error('Search reset issued RPC');
 searchFor('');await wait(()=>button('Second commit'));
 if(document.querySelector('section[aria-label=historyGraph] [aria-current=true]'))throw Error('Clearing search restored stale graph selection');
 button('First commit').click();await wait(()=>graphButtons[0].getAttribute('aria-current')==='true'&&button('added · example.txt'));
 if(graphButtons[1].hasAttribute('aria-current')||calls.at(-1).payload.commit!==a)throw Error('List selection did not synchronize graph and detail');
 button('added · example.txt').click();await wait(()=>document.querySelector('.vcs-text-comparison'));
 if(!document.querySelector('.vcs-text-comparison').textContent.includes('historical content'))throw Error('Missing historical content');
 const originalFetch=globalThis.fetch;let assetRequests=0;
 globalThis.fetch=async(url,options)=>{
  assetRequests++;
  if(!String(url).includes('vcs-assets/editor.js')||options.credentials!=='same-origin')throw Error('Incorrect editor asset request');
  return new Response('Unauthorized',{status:401});
 };
 button('historyAdvanced').click();await wait(()=>document.querySelector('#root').textContent.includes('HTTP 401'));
 if(!document.querySelector('.vcs-text-comparison')?.textContent.includes('historical content'))throw Error('Asset failure lost text fallback');
 if(assetRequests!==1)throw Error('Unexpected editor resource retry');
 button('historyBasic').click();await wait(()=>button('historyAdvanced'));
 if(document.querySelector('link[href*="editor.css"]'))throw Error('Editor stylesheet leaked after disable');
 globalThis.fetch=originalFetch;
 const countBeforeFilter=calls.length;
 const input=document.querySelector('input[aria-label="commitFileSearch"]');
 const enter=value=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));};
 enter('no-matching-file');await wait(()=>!button('added · example.txt'));
 if(document.querySelector('.vcs-text-comparison'))throw Error('Filtered file retained old diff');
 enter('');await wait(()=>button('added · example.txt'));
 if(calls.length!==countBeforeFilter)throw Error('Filtering unexpectedly called RPC');
 const select=document.querySelector('select[aria-label="commitParent"]');select.value='1';select.dispatchEvent(new Event('change',{bubbles:true}));
 await wait(()=>button('added · parent-two.txt'));
 if(document.querySelector('.vcs-text-comparison'))throw Error('Old parent diff retained');
 if(calls.at(-1).payload.parentIndex!==1)throw Error('Parent selection not forwarded');
 delayNext=true;button('added · parent-two.txt').click();await wait(()=>delayedResolve);
 const staleResolve=delayedResolve,staleSignal=delayedSignal;delayedResolve=null;
 button('Second commit').click();await wait(()=>button('added · example.txt'));
 if(!staleSignal.aborted)throw Error('Switch failed to abort old diff');
 staleResolve({path:'STALE',left:{text:''},right:{text:'STALE'},binary:false});
 await new Promise(r=>setTimeout(r,40));if(document.querySelector('#root').textContent.includes('STALE'))throw Error('Stale response displayed');
 delayNext=true;button('added · example.txt').click();await wait(()=>delayedResolve);
 root.unmount();if(!delayedSignal.aborted)throw Error('Unmount failed to cancel');
 delayedResolve({path:'STALE',left:{text:''},right:{text:'STALE'}});
 document.querySelector('#report').textContent=JSON.stringify({pass:true,browser:navigator.userAgent,steps:['search','pagination','commit','file','diff','editor-fallback','filter','parent','stale','unmount'],calls:calls.length});
 }catch(e){document.querySelector('#report').textContent=JSON.stringify({pass:false,error:String(e)});}})();
