import React from 'react';import {createRoot} from 'react-dom/client';import {flushSync} from 'react-dom';import HistoricalSegments from '../src/HistoricalSegments.jsx';
export async function checkSegments(){
 const host=document.createElement('div');document.body.appendChild(host);const root=createRoot(host),calls=[];let mode='normal',pending=[],rediscovered=0;
 const wait=async fn=>{for(let i=0;i<240;i++){if(fn())return;await new Promise(r=>setTimeout(r,25));}throw Error('Segments UI timeout: '+host.textContent.slice(0,200));};
 const value=p=>({commit:p.commit,path:p.path,oid:'b'.repeat(40),offset:p.offset,endOffset:p.offset+65536,totalBytes:131072,nextOffset:p.offset===0?65536:null,text:p.offset===0?'FIRST SEGMENT':'SECOND SEGMENT'});
 const rpc=async(e,p,signal)=>{if(e!=='vcs/tree-segment'||p.commit!=='a'.repeat(40)||p.path!=='file.txt')throw Error('Segment identity');calls.push({p,signal});if(mode==='pending')return new Promise(resolve=>pending.push(()=>resolve(value(p))));if(mode==='error')throw Error('segment failure');if(mode==='expired')throw Object.assign(Error('expired'),{code:'vcs/rediscover-required'});return value(p);};
 const button=k=>[...host.querySelectorAll('button')].find(n=>n.textContent===k),render=(repositoryId='r')=>flushSync(()=>root.render(<HistoricalSegments sessionId='s' {...{repositoryId,rpc}} commit={'a'.repeat(40)} path='file.txt' t={k=>k} onRediscover={()=>{rediscovered++;}}/>));
 try{render();if(calls.length)throw Error('Segments fetched automatically');button('segments').click();await wait(()=>host.querySelector('.monaco-editor'));if(host.querySelector('.monaco-diff-editor')||!button('previous').disabled)throw Error('Not advanced single segment');
 button('next').click();await wait(()=>host.textContent.includes('65536–131072')&&host.querySelector('.monaco-editor'));if(calls.at(-1).p.offset!==65536||!calls[0].signal.aborted||!button('next').disabled||host.textContent.includes('FIRST SEGMENT'))throw Error('Segment page not replacing');
 button('previous').click();await wait(()=>host.textContent.includes('0–65536')&&host.querySelector('.monaco-editor'));button('segments').click();await wait(()=>!host.querySelector('.monaco-editor'));if(calls.some(c=>!c.signal.aborted))throw Error('Closed segments not cancelled');
 mode='error';button('segments').click();await wait(()=>host.querySelector('[role=alert]'));mode='normal';button('retry').click();await wait(()=>host.querySelector('.monaco-editor'));button('segments').click();await wait(()=>!host.querySelector('.monaco-editor'));
 mode='expired';button('segments').click();await wait(()=>rediscovered===1);button('segments').click();mode='pending';await wait(()=>button('segments').getAttribute('aria-expanded')==='false');button('segments').click();await wait(()=>pending.length===1);const old=calls.at(-1);render('next');if(!old.signal.aborted||button('segments').getAttribute('aria-expanded')!=='false')throw Error('Repo switch retained segments');pending.forEach(done=>done());await new Promise(r=>setTimeout(r,30));if(host.querySelector('.monaco-editor')||host.textContent.includes('FIRST SEGMENT'))throw Error('Late segment revived switched repository');
 }finally{root.unmount();host.remove();}
}
