import {request as httpsRequest} from 'node:https';
import {parseSvnRevision} from './svn-revision.mjs';
// Internal primitive only. Caller must separately authorize repository identity and protocol operation.
export function createBoundedHttps({request=httpsRequest}={}){return async(url,{origin,method='GET',body='',depth,label,signal,maxBytes=2097152,timeoutMs=15000}={})=>{
 const target=new URL(url);if(target.protocol!=='https:'||target.origin!==origin||target.username||target.password||target.hash||target.href!==url||!['GET','PROPFIND','REPORT'].includes(method)||typeof body!=='string'||Buffer.byteLength(body)>65536||!Number.isInteger(maxBytes)||maxBytes<1||maxBytes>2097152||!Number.isInteger(timeoutMs)||timeoutMs<1||timeoutMs>15000)throw Error('Invalid bounded HTTPS request');if(depth!==undefined&&(method!=='PROPFIND'||depth!==0))throw Error('Invalid DAV depth');if(label!==undefined){if(method!=='PROPFIND'||depth!==0)throw Error('Invalid DAV label');parseSvnRevision(label);}const davHeaders={...(depth===0?{Depth:'0'}:{}),...(label!==undefined?{Label:label}:{})};signal?.throwIfAborted();
 return new Promise((resolve,reject)=>{let req,res,error=null,result=null,size=0;const chunks=[];
 const stop=e=>{error??=e;res?.destroy();req?.destroy();};const abort=()=>stop(signal.reason??new DOMException('HTTPS cancelled','AbortError'));const timer=setTimeout(()=>stop(new DOMException('HTTPS deadline exceeded','TimeoutError')),timeoutMs);
 const cleanup=()=>{clearTimeout(timer);signal?.removeEventListener('abort',abort);};
 try{req=request(target,{method,agent:false,rejectUnauthorized:true,maxHeaderSize:16384,headers:{...davHeaders,'Accept-Encoding':'identity','Content-Type':'text/xml; charset=utf-8','Content-Length':String(Buffer.byteLength(body))}},response=>{res=response;const status=res.statusCode??0;if(status>=300&&status<400){stop(Error('HTTPS redirects forbidden'));return;}if(status<200||status>=300){stop(Error('HTTPS status '+status));return;}if(res.headers['content-encoding']&&res.headers['content-encoding']!=='identity'){stop(Error('HTTPS compressed responses forbidden'));return;}const length=res.headers['content-length'];if(length!==undefined&&(!/^[0-9]+$/.test(length)||Number(length)>maxBytes)){stop(Error('HTTPS response exceeds byte limit'));return;}res.on('data',b=>{size+=b.length;if(size>maxBytes)stop(Error('HTTPS response exceeds byte limit'));else if(!error)chunks.push(b);});res.on('error',stop);res.on('end',()=>{if(!res.complete){stop(Error('HTTPS response incomplete'));return;}result=Buffer.concat(chunks);});});
 req.on('error',e=>{error??=e;});req.once('close',()=>{cleanup();if(error)reject(error);else if(result!==null)resolve(result);else reject(Error('HTTPS response closed before completion'));});signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();else req.end(body);
 }catch(e){cleanup();req?.destroy();reject(e);}
 });};}
