import {parseSvnRevision} from './svn-revision.mjs';
// Internal adapter: not registered by the production plugin.
const fields={describe:[],approve:['offer','explicit'],log:['token','snapshot','cursor','limit'],detail:['token','snapshot','revision'],compare:['token','snapshot','revision','id'],trace:['token','snapshot','revision','id','cursor','limit']};
export function createSvnRpc(runtime){let active=0;return async(endpoint,payload,signal)=>{const method=endpoint.startsWith('vcs/svn-')?endpoint.slice(8):'';if(!Object.hasOwn(fields,method))return {ok:false,error:{code:'vcs/not-found',message:'Unknown SVN endpoint'}};if(active>=2)return {ok:false,error:{code:'vcs/busy',message:'SVN history requests busy'}};active++;try{
 signal?.throwIfAborted();if(!payload||typeof payload!=='object'||Array.isArray(payload))throw Error('Object payload required');if(Object.keys(payload).some(k=>!['sessionId','repositoryId',...fields[method]].includes(k)))throw Error('Unknown SVN request field');for(const k of ['sessionId','repositoryId'])if(typeof payload[k]!=='string'||!payload[k]||payload[k].length>1024||payload[k].includes('\0'))throw Error('Invalid SVN Session address');
 if(method==='approve'){if(payload.explicit!==true||typeof payload.offer!=='string'||!/^[a-f0-9]{64}$/.test(payload.offer))throw Error('Explicit scoped offer required');}
 if(!['describe','approve'].includes(method)){if(typeof payload.token!=='string'||!/^[a-f0-9]{64}$/.test(payload.token))throw Error('SVN consent token required');parseSvnRevision(payload.snapshot);if(payload.revision!==undefined)parseSvnRevision(payload.revision);if(['detail','compare','trace'].includes(method)&&payload.revision===undefined)throw Error('Selected SVN revision required');if(payload.cursor!==undefined)parseSvnRevision(payload.cursor);if(payload.limit!==undefined&&(!Number.isInteger(payload.limit)||payload.limit<1||payload.limit>100))throw Error('Invalid SVN page size');if(['compare','trace'].includes(method)&&(typeof payload.id!=='string'||!/^[a-f0-9]{64}$/.test(payload.id)))throw Error('Selected SVN change ID required');}
 const {sessionId,repositoryId,...options}=payload,value=await runtime[method]({sessionId,repositoryId},{...options,signal});signal?.throwIfAborted();return {ok:true,value};
 }catch(error){return {ok:false,error:{code:signal?.aborted?'vcs/cancelled':'vcs/operation-failed',message:error instanceof Error?error.message:String(error)}};}finally{active--;}};}
