import {watchSvnExpiry} from './svn-ui-expiry.mjs';
import React,{useEffect,useState} from 'react';
// Not mounted in production until a verified remote transport exists.
export default function SvnConsent(props){return <Scoped key={JSON.stringify([props.sessionId,props.repositoryId])} {...props}/>;}
function Scoped({sessionId,repositoryId,rpc,t,onApproved,onRediscover}){
 const [open,setOpen]=useState(false),[offer,setOffer]=useState(null),[checked,setChecked]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{if(!open)return;const controller=new AbortController();setOffer(null);setChecked(false);setError('');setBusy(true);rpc('vcs/svn-describe',{sessionId,repositoryId},controller.signal).then(v=>{if(!controller.signal.aborted)setOffer(v);}).catch(e=>{if(!controller.signal.aborted){setError(e.message);if(e.code==='vcs/rediscover-required')onRediscover();}}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[open,sessionId,repositoryId,retry]);
 const [attempt,setAttempt]=useState(0);
 useEffect(()=>{if(!open||!offer||offer.expiresAt===undefined)return;const expire=()=>{setOffer(null);setChecked(false);setAttempt(0);setBusy(false);setError(t('svnOfferExpired'));};try{return watchSvnExpiry(offer.expiresAt,expire);}catch{expire();}},[open,offer]);
 useEffect(()=>{if(!attempt||!open||!offer)return;const controller=new AbortController();setBusy(true);setError('');rpc('vcs/svn-approve',{sessionId,repositoryId,offer:offer.offer,explicit:true},controller.signal).then(v=>{if(!controller.signal.aborted)onApproved(v);}).catch(e=>{if(!controller.signal.aborted){setError(e.message);setChecked(false);if(e.code==='vcs/rediscover-required')onRediscover();}}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[attempt,open,offer]);
 return <section><button aria-expanded={open} onClick={()=>{setAttempt(0);setOpen(v=>!v);}}>{t('svnConsentReview')}</button>{open&&<><p>{t('svnConsentScope')}</p>{error&&<p role='alert'>{error} <button disabled={busy} onClick={()=>{setAttempt(0);setRetry(n=>n+1);}}>{t('retry')}</button></p>}{offer&&<><dl>{['origin','root','uuid','scope'].map(k=><React.Fragment key={k}><dt>{k}</dt><dd><code>{offer[k]}</code></dd></React.Fragment>)}</dl>{!offer.remoteEnabled?<p role='status'>{t('svnRemoteDisabled')}</p>:<><label><input type='checkbox' checked={checked} disabled={busy} onChange={e=>setChecked(e.target.checked)}/>{t('svnConsentExplicit')}</label><button disabled={busy||!checked} onClick={()=>setAttempt(n=>n+1)}>{t('svnConsentApprove')}</button></>}</>}{busy&&<p role='status'>{t('loading')}</p>}</>}</section>;
}
